backend/use-crane-to-push-docker-images

diff --git a/.github/workflows/nix.yaml b/.github/workflows/nix.yaml
--- a/.github/workflows/nix.yaml
+++ b/.github/workflows/nix.yaml
@@ -4,11 +4,13 @@ on:
   push:
     branches: 
       - "main"
+      - "backend/use-crane-to-push-docker-images"
       - "prodHotPush-Common"
   pull_request:
     types: [opened, synchronize, reopened, closed]
     branches: 
       - "main"
+      - "backend/use-crane-to-push-docker-images"
       - "prodHotPush-Common"
   workflow_dispatch:
 
@@ -58,19 +60,16 @@ jobs:
           fi
           echo "has_backend=${has_backend}" >> $GITHUB_OUTPUT
           echo "Label check result: ${has_backend}"
-
       - name: Check docker push conditions
         id: check-docker-push
         run: |
-          # Moving the docker push conditions here from the build job
-          if [[ "${{ github.ref }}" == "refs/heads/main" || 
+          if [[ "${{ github.ref }}" == "refs/heads/backend/use-crane-to-push-docker-images" || 
                 "${{ github.ref }}" == "refs/heads/prodHotPush-Common" || 
                 "${{ github.event.pull_request.merged }}" == "true" ]]; then
             echo "should_push_docker=true" >> $GITHUB_OUTPUT
           else
             echo "should_push_docker=false" >> $GITHUB_OUTPUT
           fi
-
   build:
     needs: [check-conditions]
     if: needs.check-conditions.outputs.should-proceed == 'true' && needs.check-conditions.outputs.has-backend == 'true'
@@ -79,24 +78,24 @@ jobs:
         include:
           - system: x86_64-linux
             host: x86_64-linux
+            arch: amd64
           - system: aarch64-darwin
             host: aarch64-darwin
           - system: aarch64-linux
             host: aarch64-darwin
+            arch: arm64
     runs-on: ${{ matrix.host }}
     outputs:
-      docker-image-name: ${{ steps.docker.outputs.image_name }}
+      docker-image-name: ${{ steps.docker.outputs.base_image }}
     steps:
       - name: Check matrix conditions
         id: check-conditions
         run: |
-          # Should build check (skip aarch64-linux on non-main)
-          if [[ "${{ matrix.system }}" == "aarch64-linux" && "${{ github.ref }}" != "refs/heads/main" ]]; then
+          if [[ "${{ matrix.system }}" == "aarch64-linux" && "${{ github.ref }}" != "refs/heads/backend/use-crane-to-push-docker-images" ]]; then
             echo "should_build=false" >> $GITHUB_OUTPUT
           else
             echo "should_build=true" >> $GITHUB_OUTPUT
           fi
-
       - name: Checkout repository
         if: steps.check-conditions.outputs.should_build == 'true'
         uses: actions/checkout@v4
@@ -107,24 +106,54 @@ jobs:
           path: ~/.cache/nix
           key: nixcache-${{ matrix.host }}-${{ matrix.system }}
 
-      - name: Build all flake outputs
-        if: steps.check-conditions.outputs.should_build == 'true'
-        run: |
-          om ci run --systems "${{ matrix.system }}" --no-out-link -- -v
-
-      - name: Build Docker image
+      - name: Build And Push Docker image
         id: docker
-        if: steps.check-conditions.outputs.should_build == 'true' && matrix.system == 'x86_64-linux' && needs.check-conditions.outputs.should-push-docker == 'true'
+        if: steps.check-conditions.outputs.should_build == 'true' && (matrix.system == 'x86_64-linux' || matrix.system == 'aarch64-linux') && needs.check-conditions.outputs.should-push-docker == 'true'
+        env:
+          DOCKER_REGISTRY: ghcr.io
         run: |
-          nix build .#dockerImage -o docker-image.tgz
-          echo "image_name=$(nix eval --raw .#dockerImage.imageName):$(nix eval --raw .#dockerImage.imageTag)" >> $GITHUB_OUTPUT
-      
-      - name: Upload Docker image
-        if: steps.check-conditions.outputs.should_build == 'true' && matrix.system == 'x86_64-linux' && needs.check-conditions.outputs.should-push-docker == 'true'
-        uses: actions/upload-artifact@v4
-        with:
-          name: docker-image
-          path: docker-image.tgz
+          nix build .#packages.${{ matrix.system }}.dockerImage
+    
+          BASE_IMAGE="$(nix eval --raw .#packages.${{ matrix.system }}.dockerImage.imageName):$(nix eval --raw .#packages.${{ matrix.system }}.dockerImage.imageTag)"
+          echo "base_image=${BASE_IMAGE}" >> $GITHUB_OUTPUT
+
+          gunzip -c ./result > image.tar || cp ./result image.tar
+          nix profile install nixpkgs#crane
+          export PATH="$HOME/.nix-profile/bin:$PATH"
+          echo "${{ secrets.GITHUB_TOKEN }}" | crane auth login ${DOCKER_REGISTRY} -u "${{ github.actor }}" --password-stdin
+          crane push image.tar "${DOCKER_REGISTRY}/${BASE_IMAGE}-${{ matrix.arch }}"
+          crane auth logout ${DOCKER_REGISTRY}
+
+  create-manifest:
+    needs: [build, check-conditions]
+    if: needs.check-conditions.outputs.should-push-docker == 'true'
+    env:
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      IMAGE_NAME: ${{ needs.build.outputs.docker-image-name }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Create and push MultiArch manifest
+        run: |
+          echo "$GITHUB_TOKEN" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
+
+          # Check if both architecture-specific images exist
+          if docker manifest inspect "${IMAGE_NAME}-amd64" > /dev/null 2>&1 && \
+             docker manifest inspect "${IMAGE_NAME}-arm64" > /dev/null 2>&1; then
+            # Create the manifest
+            docker manifest create "$IMAGE_NAME" \
+                --amend "${IMAGE_NAME}-amd64" \
+                --amend "${IMAGE_NAME}-arm64"
+
+            # Push the manifest
+            docker manifest push "$IMAGE_NAME"
+          else
+            echo "One or more architecture-specific images are missing"
+            exit 1
+          fi
+
+          docker logout ghcr.io
+
+
   # The previous job would have already built for macOS but we must do it again
   # from NixOS host (via remote builder protocol) so as to populate its local
   # Nix store, and thus provide macOS binaries as part of our Nix cache.
@@ -143,22 +172,3 @@ jobs:
       - name: Build all flake outputs
         run: |
           om ci run --systems "${{ matrix.system }}" --no-out-link -- -v
-
-  push-docker:
-    needs: [build, check-conditions]
-    runs-on: ubuntu-latest
-    if: needs.check-conditions.outputs.should-push-docker == 'true' && needs.check-conditions.outputs.has-backend == 'true'
-    steps:
-      - name: Download Docker image
-        uses: actions/download-artifact@v4
-        with:
-          name: docker-image
-
-      - name: Push Docker image
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          echo "$GITHUB_TOKEN" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
-          docker load < docker-image.tgz
-          docker push ${{ needs.build.outputs.docker-image-name }}
-          docker logout ghcr.io
